language: node_js
node_js:
- 0.12.2
before_install:
- npm cache clean
- npm update npm -g
- npm install -g bower grunt-cli codeclimate-test-reporter
install:
- npm install --save-dev
- bower install
script: grunt test
after_script:
- CODECLIMATE_REPO_TOKEN=6b66bc0cfc18d986b1467f0bedb68fe6f2e4ce7954efa5703ef2d1dfe1b2b2d6
  codeclimate < coverage/lcov.info
- node build.js
env:
  global:
    secure: aV0qm6yCJ/Y3T6HI0X5yITK6NzRnluvpcTpcqtMlAvvsThcT6ct8h+/Qydt22YSSeyfmwlLbe24SZ2PKhRX96a4xvt1UrGwzw9RkjPm5X7VUbeNX+CE/idbzbI/vLaurKmQp19iKPU1MzVdbgKlY+uSH/pRVmgVFyTl7flnSfj8=
