language: node_js
node_js:
    - "0.10.33"
before_install:
    - npm cache clean
    - npm update npm -g
    - npm install -g bower grunt-cli codeclimate-test-reporter
    - curl -L https://get.rvm.io | bash -s stable --ruby=1.9.3
    - gem install awestruct bundler
install:
    - npm install --save-dev
    - bower install
script: grunt test
after_script:
    - CODECLIMATE_REPO_TOKEN=6b66bc0cfc18d986b1467f0bedb68fe6f2e4ce7954efa5703ef2d1dfe1b2b2d6 codeclimate < coverage/lcov.info
    - node build.js
    - awestruct -P composer -g --deploy